package comm;

public enum Comands {
	E_LEFT, E_RIGHT, E_UP, E_DOWN, V_CCW, V_CW, V_ACELL, V_DECELL, FIRE, BRAINSWAP,
	DROP_ITEM_0,DROP_ITEM_1, DROP_ITEM_2, DROP_ITEM_3, DROP_ITEM_4, DROP_ITEM_5,DROP_ITEM_6,DROP_ITEM_7,DROP_ITEM_8,DROP_ITEM_9
}